version: 0.2

phases: 
  install:
    commands:
      - echo "Install Nodejs and NPM"
      - sudo apt update
      - sudo apt install -y nodejs npm
      - node -v
      - npm -v
  pre_build:
    commands:
      - echo "Installing dependencies back"
      - npm install
  build:
    commands:
      - echo "Creating the build folder"
      - npm run build

artifacts:
  files:
    - 'Dockerfile'
    - 'nginx/**/*'
<<<<<<< HEAD
    - 'build/**/*'
Footer
© 2022 GitHub, Inc.
Footer navigation
Terms
P
=======
    - 'build/**/*'
>>>>>>> bb044d8d2c7bd8f840f747f4326cdb72ff8749c6
